  mongo:
    # MongoDB的适配器
    adapter_type: NoSqlDb
    plugin:
      module_name: HiveNetNoSql.mongo
      class: MongoNosqlDriver
      instantiation: true
      init_kwargs:
        # 支持的参数见MongoNosqlDriver的初始化函数, 注意pool_config和driver_config参数如果不设置应删除配置项
        connect_config:
          host: "127.0.0.1"
          port: 27017
          dbname: admin
          username: root
          password: "123456"