  nacos:
    # nacos类型的配置中心设置
    plugin:
      path: adapter/config_nacos.py
      class: NacosConfigAdapter
      instantiation: true
      init_kwargs:
        # ******************************************
        # 固定位置的初始化参数
        # init_config: dict, 客户端连接配置, acos配置中心支持的初始化参数包括:
        #   server_addresses: str, 必填, 服务端地址, 可以通过逗号分隔多个地址
        #     例如: "192.168.3.4:8848" or "https://192.168.3.4:443" or "http://192.168.3.4:8848,192.168.3.5:8848" or "https://192.168.3.4:443,https://192.168.3.5:443"
        #   endpoint: str, 配置中心物理隔离参数, 可以不设置
        #   ak: str, 阿里云MES的ak认证方案, 可以不设置
        #   sk: str, 阿里云MES的sk认证方案, 可以不设置
        #   username: str, 设置了登录认证的用户名
        #   password: str, 设置了登录认证的密码
        #   auto_create_mamespace: bool, 命名空间不存在时是否自动创建, 默认为True
        #   default_options, dict, nacos默认参数值, 所支持的参数详见nacos的sdk
        #     TIMEOUT, float, 默认超时时间, 单位为秒
        #     ...
        # namespace: str, 指定当前连接要设置的命名空间, 如果设置为~代表直接使用base_config.namespace
        # ******************************************
        init_config:
          server_addresses: 127.0.0.1:8848
          endpoint: ~
          ak: ~
          sk: ~
          username: ~
          password: ~
          auto_create_mamespace: true
          default_options: ~
        namespace: ~