  serial_number_standalone:
    # 单机版本的序列服务适配器
    adapter_type: SerialNumber
    plugin:
      path: extend/serial_number_standalone.py
      class: StandaloneSerialNumberAdapter
      instantiation: True
      init_kwargs:
        init_config:
          store_path: "serial_number_data"  # 持久化存储文件目录
          overtime: 3.0
          wait_delay: 0.1
        init_serial_infos:
          # 全局流水号序列, 10位
          globSeqNum:
            max_num: 9999999999
          # 系统流水号序列, 12位
          sysSeqNum:
            max_num: 999999999999
          # 接口流水号序列, 10位
          infSeqNum:
            max_num: 9999999999
        logger_id: sysLogger
