  sanic:
    # Sanic类型web服务器适配器配置
    plugin:
      path: adapter/web_sanic.py
      class: SanicWebAdapter

    host: ~
    port: ~
    logger: sysLogger
    wsgi_start: false

    server_formaters:
      - SanicCommonFormater

    init_config:
      # SanicServer运行参数字典(请参考Sanic官方文档)
      run_config:
        workers: 1  # 工作线程数
        debug: false  # 是否开启debug模式(生产部署请关闭)
        access_log: false  # 启用请求访问日志(生产部署请关闭)
      auto_trace: false  # 是否开启http的trace功能(允许客户端TRACE请求时原样返回收到的报文内容)