# ******************************************
# services: 服务加载清单
#   Item Key: 需加载的服务标识
#     common_config: list, 指定需复用的通用配置标识, 按清单标识从后往前覆盖
#     sys_id: str, 服务所属系统标识
#     module_id: str, 服务所属模块标识
#     enable_service: bool, 是否启用服务, 如果为false则不对外发布服务, 仅支持本地调用, 默认为true
#     allow_local_call: bool, 是否允许服务本地调用(相同服务名的情况可直接调用本地方法), 默认为false
#     uri: str, 服务标识路径(访问路径)
#     enable_tracer: bool, 是否启用调用链, 默认为false
#     inf_logging: str, 使用的报文信息日志记录插件标识
#     inf_check: str, 使用的请求报文信息检查插件标识
#     formater: str, 使用的报文转换插件标识
#     kv_type_trans_mapping: dict, key-value格式入参的转换字典, 如果不设置参数均默认为字符串格式
#       Para Key: str, 要转换的参数名, 值为类型转换函数对应的字符串
#       ...
#
#     web_server: dict, 自定义注: 为services.yaml配置中services下服务配置标识的完整配置字典
#       Item Key: 配置所对应的Web服务器标识
#         ...: Web服务器自有配置
#
#     trace_options: dict, 当前服务私有调用链配置, 如果不配置则使用调用链插件所配置的参数
#       operation_name_para: str, 操作名称, 格式为参数表达式
#         注: 如果不设置默认为服务的标识
#       self_tag_paras: dict, 需要从请求对象获取并放入Tags的参数字典
#         每个参数的key为要送入Tags的标识名, value为获取参数, 格式为参数表达式
#       self_baggage_paras: dict, 需要从请求对象获取并放入SpanContext中Baggage传递到后续调用的参数字典
#         key为要送入Baggage的标识名, value为参数表达式
#       self_resp_tag_paras: dict, 需要从需处理函数的返回对象获取并放入Tags的的参数字典
#         每个参数的key为要送入Tags的标识名, value为参数表达式
#       trace_all_exception: bool, 是否记录所有异常错误(默认为true), 如果为false则按照trace_exceptions所设定的异常类型进行记录
#       trace_exceptions: List[str], 要记录的异常错误清单, 字符格式, 包含模块名
#         例如: ModuleNotFoundError, module_name.ERROR
#         注: python原生的异常属于builtins模块, 这种情况无需写模块名
#       get_response_error_func: dict - 判断请求函数返回值是否错误的自定义函数插件配置, 标准的plugin模式定义
#
#     plugin: dict, 服务入口函数需加载的插件配置
#       注: 具体参考插件加载的通用配置
#
#     naming: dict, 注册中心的注册参数, 也可以主动设置为 ~ (None) 来不注册服务(需要注意此时对应的common_config参数也不能设置naming参数)
#       service_name: str, 注册的服务名, 建议与服务标识一致, 如果不设置则直接使用服务标识
#       group_name: str, 所属分组, 如不传则默认为'DEFAULT_GROUP'
#       metadata: dict, 服务的元数据配置
#         protocol: str, 访问协议, 例如指定http/https
#         uri: str, 服务访问路径, 如果有设置metadata并且uri没有设置, 则自动获取服务参数中的uri进行替换
#         network: dict, 服务访问的默认网络通讯参数
#         headers: dict, 服务访问的默认header参数
#       naming_config: dict, 注册中心适配器的特定配置
#         Item Key: 当前所使用的注册中心适配器标识
#           ...: 注册中心适配器需要传入的参数
# ******************************************
services:


# ******************************************
# common_config: 可复用的通用配置, 用于减少重复的配置
# 注: 服务器清单的自有配置将按字典形式覆盖通用配置
# ******************************************
common_config:
